import { Inter, Roboto } from "next/font/google"
import localFont from "next/font/local";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { ThemeProvider } from "@/components/ThemeProvider";
import Authprovider from "@/context/Authprovider";
import { Headset } from "lucide-react";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from "@/components/ui/dialog"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import Footer from "@/components/Footer";

const inter = Inter({ subsets: ["latin"], });
const roboto = Roboto({ weight: ['400', '500', '700', '700'], subsets: ["latin"] });

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={` ${inter.className} antialiased relative`}
      >
        <Authprovider>
          <ThemeProvider attribute="class" defaultTheme="light">
            <Navbar></Navbar>
            {children}
            <span className="fixed top-1/2 right-6  bg-slate-400 hover:bg-[#25bb4a]  text-white py-2 px-4 cursor-pointer transition-all duration-500 z-50">
              <Dialog>
                <DialogTrigger asChild>
                  <Headset />
                </DialogTrigger>
                <DialogContent className="sm:max-w-[425px]">
                  <DialogHeader>
                    <DialogTitle>Edit profile</DialogTitle>
                    <DialogDescription>
                      Make changes to your profile here. Click save when you're done.
                    </DialogDescription>
                  </DialogHeader>
                  <div className="grid gap-4 py-4">
                    <div className="grid grid-cols-4 items-center gap-4">
                      <Label htmlFor="name" className="text-right">
                        Name
                      </Label>
                      <Input id="name" defaultValue="Pedro Duarte" className="col-span-3" />
                    </div>
                    <div className="grid grid-cols-4 items-center gap-4">
                      <Label htmlFor="username" className="text-right">
                        Username
                      </Label>
                      <Input id="username" defaultValue="@peduarte" className="col-span-3" />
                    </div>
                  </div>
                  <DialogFooter>
                    <button type="submit">Save changes</button>
                  </DialogFooter>
                </DialogContent>
              </Dialog>

            </span>
             <Footer/>
          </ThemeProvider>
        </Authprovider>


      </body>
    </html>
  );
}
